function p2DViewSize(obj, varargin)
    obj.h2DViewPanel.Units = 'pixels';
    p = obj.h2DViewPanel.Position;
    ViewPanelPosition = struct('left', p(1), 'bottom', p(2), 'width', p(3), 'height', p(4));

    HORIZONTAL_AXIS_MARGIN = 54;
    VERTICAL_AXIS_MARGIN = 44;

    rowWidth = max(ViewPanelPosition.width - 2 * HORIZONTAL_AXIS_MARGIN - 76, 1);
    rowHeight = max(ViewPanelPosition.height - VERTICAL_AXIS_MARGIN - 8, 200);

    MainViewPosition = struct(...
        'left', HORIZONTAL_AXIS_MARGIN, ...
        'bottom', VERTICAL_AXIS_MARGIN, ...
        'width', max(floor(rowWidth * .75), 200), ...
        'height', rowHeight);
    set([obj.h2DMainViewAxes, obj.h2DMainViewOutlineAxes, obj.h2DMainViewTickAxes], ...
        'Units', 'pixels', ...
        'Position', [MainViewPosition.left, MainViewPosition.bottom, ...
        MainViewPosition.width, MainViewPosition.height]);

    ZScrollPosition = struct(...
        'left', MainViewPosition.left + MainViewPosition.width + 1, ...
        'bottom', VERTICAL_AXIS_MARGIN, ...
        'width', 75, ...
        'height', rowHeight);
    set(obj.h2DZScrollAxes, 'Units', 'pixels', ...
        'Position', [ZScrollPosition.left, ZScrollPosition.bottom, ...
        ZScrollPosition.width, ZScrollPosition.height]);

    ProjectionPosition = struct(...
        'left', ZScrollPosition.left + ZScrollPosition.width + 1, ...
        'bottom', VERTICAL_AXIS_MARGIN, ...
        'width', max(floor(rowWidth * .25), 100), ...
        'height', rowHeight);
    set([obj.h2DProjectionViewAxes, obj.h2DProjectionViewTickAxes], ...
        'Units', 'pixels', ...
        'Position', [ProjectionPosition.left, ProjectionPosition.bottom, ...
        ProjectionPosition.width, ProjectionPosition.height]);

    obj.updateXYAxes();
    obj.updateScrollPatch();
end
% ---------------------------------------------------------------------------
% Copyright (C) 2025 MBF Bioscience
% 
% ScanImage (R) 2025 is software to be used under the purchased terms
% Code may be modified, but not redistributed without the permission
% of MBF Bioscience
% 
% MBF BIOSCIENCE MAKES NO WARRANTIES, EXPRESS OR IMPLIED, WITH
% RESPECT TO THIS PRODUCT, AND EXPRESSLY DISCLAIMS ANY WARRANTY OF
% MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
% IN NO CASE SHALL MBF BIOSCIENCE BE LIABLE TO ANYONE FOR ANY
% CONSEQUENTIAL OR INCIDENTAL DAMAGES, EXPRESS OR IMPLIED, OR UPON ANY OTHER
% BASIS OF LIABILITY WHATSOEVER, EVEN IF THE LOSS OR DAMAGE IS CAUSED BY
% MBF BIOSCIENCE'S OWN NEGLIGENCE OR FAULT.
% CONSEQUENTLY, MBF BIOSCIENCE SHALL HAVE NO LIABILITY FOR ANY
% PERSONAL INJURY, PROPERTY DAMAGE OR OTHER LOSS BASED ON THE USE OF THE
% PRODUCT IN COMBINATION WITH OR INTEGRATED INTO ANY OTHER INSTRUMENT OR
% DEVICE.  HOWEVER, IF MBF BIOSCIENCE IS HELD LIABLE, WHETHER
% DIRECTLY OR INDIRECTLY, FOR ANY LOSS OR DAMAGE ARISING, REGARDLESS OF CAUSE
% OR ORIGIN, MBF BIOSCIENCE MAXIMUM LIABILITY SHALL NOT IN ANY
% CASE EXCEED THE PURCHASE PRICE OF THE PRODUCT WHICH SHALL BE THE COMPLETE
% AND EXCLUSIVE REMEDY AGAINST MBF BIOSCIENCE.
% ---------------------------------------------------------------------------
