function rebuildLegend(obj)
    import scanimage.guis.roigroupeditor.LegendAttributes;
    % delete old items
    delete(obj.hLegendGrid.Children);

    %% Attributes
    % default legend items which only need binding
    Attributes = [...
        LegendAttributes(...
        'name', 'Scanner Field of View',...
        'lineColor', most.constants.Colors.yellow,...
        'lineStyle', ':',...
        'localBinding', 'showScannerFov')...
        LegendAttributes(...
        'name', 'Editor Z Plane',...
        'lineColor', most.constants.Colors.orange,...
        'lineStyle', '-',...
        'localBinding', 'showEditorZ')...
        LegendAttributes(...
        'name', 'Imaging Z Planes',...
        'lineColor', most.constants.Colors.white,...
        'lineStyle', '-',...
        'fillColor', 'none',...
        'localBinding', 'showImagingZs')...
        LegendAttributes(...
        'name', 'Currently Selected ROI',...
        'lineColor', most.constants.Colors.green,...
        'lineStyle', '-',...
        'localBinding', 'showSelectedRoi')...
        LegendAttributes(...
        'name', 'Other ROIs',...
        'lineColor', most.constants.Colors.red,...
        'lineStyle', '-',...
        'localBinding', 'showOtherRois')...
        LegendAttributes(...
        'name', 'Tile View', ...
        'lineColor', most.constants.Colors.cyan, ...
        'lineStyle', '-', ...
        'localBinding', 'showTileView')];
    numDefaultBoundItems = length(Attributes);
    numContextImages = numel(obj.hContextImages);
    obj.nLegendItems = numDefaultBoundItems + numContextImages + 2; % + power box image + add from file button
    obj.resizeLegend();

    for iItem = 1:numDefaultBoundItems
        ItemAttributes = Attributes(iItem);
        Item = makeItem(obj.hLegendGrid, ItemAttributes);

        Item.hCb.hCtl.KeyPressFcn = @obj.keyPressFcn;
        Item.hCb.bindings = {obj, ItemAttributes.localBinding, 'Value'};
    end

    %% Power Box Context
    PowerBoxAttributes = LegendAttributes(...
        'name', 'Power boxes', ...
        'lineColor', most.constants.Colors.orange, ...
        'lineStyle', '-', ...
        'fillColor', most.constants.Colors.red, ...
        'localBinding', 'showPowerBoxes');
    PowerBoxItem = makeItem(obj.hLegendGrid, PowerBoxAttributes);

    PowerBoxItem.hCb.hCtl.KeyPressFcn = @obj.keyPressFcn;
    PowerBoxItem.hCb.bindings = {obj, PowerBoxAttributes.localBinding, 'Value'};
    hPowerBoxFlow = PowerBoxItem.hContainer;

    powerBoxNames = arrayfun(@(pb)pb.name, obj.hModel.hBeams.powerBoxes, 'UniformOutput', false);
    powerBoxNames = [{''} powerBoxNames];
    obj.pmSelectedPowerBox = most.gui.uicontrol( ...
        'parent',hPowerBoxFlow, ...
        'string', powerBoxNames, ...
        'style','popupmenu', ...
        'RelPosition', [123 33 86 28], ...
        'WidthLimits', [80 130], ...
        'KeyPressFcn', @obj.hEditorGui.keyPressFcn, ...
        'tag','pmSelectPb', ...
        'callback',@obj.selectPowerBox);

    hPowerBoxFlow = most.gui.uiflowcontainer( ...
        'parent',PowerBoxItem.hContainer,'margin',3,'flowdirection','righttoleft');
    hAddPowerBoxButton = most.gui.uicontrol(...
        'parent', hPowerBoxFlow,'tag','pbAddPb',...
        'string', 'Add',...
        'callback', @obj.addPowerBox);
    set(hAddPowerBoxButton, 'WidthLimits', [40 40]);

    %% Context Images
    for iItem = 1:numContextImages
        ContextImage = obj.hContextImages(iItem);
        ItemAttributes = ContextImage.getLegendAttributes();
        Item = makeItem(obj.hLegendGrid, ItemAttributes);
        ContextImage.decorateLegendItem(Item);

        Item.hCb.hCtl.KeyPressFcn = @obj.keyPressFcn;
        if ~isempty(ItemAttributes.localBinding)
            Item.hCb.bindings = {obj, ItemAttributes.localBinding, 'Value'};
        end
    end

    %% make "add image from file" button
    hItemContainer = most.gui.uiflowcontainer('parent',obj.hLegendGrid,...
        'FlowDirection','LeftToRight');
    most.gui.uicontrol('parent',hItemContainer,...
        'string','Add Image From File',...
        'callback', @(varargin)scanimage.guis.roigroupeditor.TiffContextImage(obj),...
        'KeyPressFcn',@obj.keyPressFcn);
end

function Item = makeItem(Parent, ItemAttributes)
    persistent colorScaling;
    if isempty(colorScaling)
        colorScaling = rand(6);
    end

    Item.hContainer = most.gui.uiflowcontainer('parent', Parent,...
        'FlowDirection','LeftToRight');

    hUP = uipanel('parent',Item.hContainer,'bordertype','none');
    set(hUP, 'WidthLimits', 30*ones(1,2));

    hAx = most.idioms.axes( ...
        'parent',hUP, ...
        'box','on','Color','k',...
        'XTick',[],'XTickLabel',[], ...
        'YTick',[],'YTickLabel',[],...
        'xlim', [0 1],'ylim', [0 1],'CLim',[0 1]);

    Item.hCb = most.gui.uicontrol( ...
        'parent', Item.hContainer,...
        'style', 'checkbox',...
        'string', ItemAttributes.name, ...
        'KeyPressFcn', @obj.keyPressFcn);

    IconSurface = surface([.1 .9], [.1 .9], [0 0; 0 0],...
        'Parent', hAx, ...
        'EdgeColor', ItemAttributes.lineColor, ...
        'LineWidth', 2, 'LineStyle', ItemAttributes.lineStyle);

    if strcmp(ItemAttributes.fillColor, 'none')
        IconSurface.FaceColor = ItemAttributes.fillColor;
    else
        sz = size(colorScaling,1);
        cData = [];
        cData(1,1,:) = ItemAttributes.fillColor;
        cData = repmat(cData,sz,sz,1) .* repmat(colorScaling,1,1,3);
        IconSurface.FaceColor = 'texturemap';
        IconSurface.CData = cData;
    end
end
% ---------------------------------------------------------------------------
% Copyright (C) 2025 MBF Bioscience
% 
% ScanImage (R) 2025 is software to be used under the purchased terms
% Code may be modified, but not redistributed without the permission
% of MBF Bioscience
% 
% MBF BIOSCIENCE MAKES NO WARRANTIES, EXPRESS OR IMPLIED, WITH
% RESPECT TO THIS PRODUCT, AND EXPRESSLY DISCLAIMS ANY WARRANTY OF
% MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
% IN NO CASE SHALL MBF BIOSCIENCE BE LIABLE TO ANYONE FOR ANY
% CONSEQUENTIAL OR INCIDENTAL DAMAGES, EXPRESS OR IMPLIED, OR UPON ANY OTHER
% BASIS OF LIABILITY WHATSOEVER, EVEN IF THE LOSS OR DAMAGE IS CAUSED BY
% MBF BIOSCIENCE'S OWN NEGLIGENCE OR FAULT.
% CONSEQUENTLY, MBF BIOSCIENCE SHALL HAVE NO LIABILITY FOR ANY
% PERSONAL INJURY, PROPERTY DAMAGE OR OTHER LOSS BASED ON THE USE OF THE
% PRODUCT IN COMBINATION WITH OR INTEGRATED INTO ANY OTHER INSTRUMENT OR
% DEVICE.  HOWEVER, IF MBF BIOSCIENCE IS HELD LIABLE, WHETHER
% DIRECTLY OR INDIRECTLY, FOR ANY LOSS OR DAMAGE ARISING, REGARDLESS OF CAUSE
% OR ORIGIN, MBF BIOSCIENCE MAXIMUM LIABILITY SHALL NOT IN ANY
% CASE EXCEED THE PURCHASE PRICE OF THE PRODUCT WHICH SHALL BE THE COMPLETE
% AND EXCLUSIVE REMEDY AGAINST MBF BIOSCIENCE.
% ---------------------------------------------------------------------------
