function makePanel(obj, GuiParent)
    % https://undocumentedmatlab.com/articles/matlab-layout-managers-uicontainer-and-relatives
    % for uigridcontainer objects
    MainRowGrid = uigridcontainer('v0' ...
        , 'Parent', GuiParent ...
        , 'GridSize', [2, 1], 'VerticalWeight', [1, 2]);
    set(MainRowGrid, 'Units', 'points', 'Margin', 5, 'Units', 'normalized');

    %% Identifier Grid
    % Wavelength and Serial number selector

    % label, interactible, response
    IdentifierFlow = uiflowcontainer('v0', 'Parent', MainRowGrid, 'FlowDirection', 'TopDown');
    IdentifierGrid = uigridcontainer('v0', 'Parent', IdentifierFlow ...
        , 'GridSize', [3, 3], 'HorizontalWeight', [2, 3, 3] ...
        , 'Units', 'points', 'Margin', 1);
    set(IdentifierGrid, 'HeightLimits', [86, 86]);

    % wavelength row
    most.gui.staticText('Parent', IdentifierGrid ...
        , 'String', 'Wavelength (nm):' ...
        , 'HorizontalAlignment', 'right' ...
        );
    obj.WavelengthEdit = uicontrol(IdentifierGrid ...
        , 'Style', 'edit' ...
        , 'UserData', struct('DisplayFormat', '%.3f nm') ...
        , 'Callback', @(Edit,~)formatAndUpdateWavelengthString(obj, Edit.String));
    LampFlow = uiflowcontainer('v0', 'Parent', IdentifierGrid, 'FlowDirection', 'LeftToRight');
    obj.WavelengthColorPanel = uipanel(LampFlow, 'BorderType', 'line', 'HighlightColor', 'k');
    set(obj.WavelengthColorPanel, 'Units', 'points', 'WidthLimits', [30, 30]);

    % serial number row
    most.gui.staticText('Parent', IdentifierGrid ...
        , 'HorizontalAlignment', 'right'...
        , 'String', 'Serial Number:' ...
        );

    CenteredPopup = uigridcontainer('v0', 'Parent', IdentifierGrid ...
        , 'GridSize', [3, 1], 'VerticalWeight', [1, 2, 1] ...
        , 'Margin', 0.1 ...
        );
    uipanel(CenteredPopup, 'BorderType', 'none'); % filler
    obj.SerialNumberPopupMenu = uicontrol(CenteredPopup ...
        , 'Style', 'popupmenu' ...
        , 'String', " " ... % populated by redraw.
        );

    obj.DetectorLabel = most.gui.staticText('Parent', IdentifierGrid ...
        , 'String', 'N/A' ...
        , 'FontSize', 10, 'FontWeight', 'bold' ...
        , 'HorizontalAlignment', 'left' ...
        );

    % auto on row
    most.gui.staticText('Parent', IdentifierGrid ...
        , 'String', 'Auto-Enable:' ...
        , 'HorizontalAlignment', 'right' ...
        );

    obj.AutoOnCheckbox = uicontrol(IdentifierGrid ...
        , 'Style', 'checkbox' ...
        , 'Tooltip', 'i.e. AutoOn. Enable the PMT whenever acquisition is started.' ...
        );

    %% PMT Controls Grid
    ControlPanel = uipanel('Parent', MainRowGrid, 'Title', 'Control Panel');
    ControlFlow = uiflowcontainer('v0', 'Parent', ControlPanel, 'FlowDirection', 'TopDown');
    StatusGrid = uigridcontainer('v0', 'Parent', ControlFlow, 'GridSize', [1, 2]);
    set(StatusGrid, 'Units', 'points', 'HeightLimits', [40, 40]);

    % live status row
    % live apply column
    LiveModeFlow = uiflowcontainer('v0', 'Parent', StatusGrid, 'FlowDirection', 'LeftToRight');
    obj.LiveModeToggle = uicontrol(LiveModeFlow ...
        , 'Style', 'checkbox' ...
        , 'String', 'Live Apply Mode' ...
        , 'Callback', @(Toggle,~)obj.toggleLiveMode(Toggle.Value == Toggle.Max) ...
        , 'Enable', 'off' ...
        , 'BackgroundColor', 'y' ...
        ); % initially off so that the selected PMT is set properly.
    set(obj.LiveModeToggle, 'Units', 'points', 'WidthLimits', [110, 110]);

    % power controls column
    MainPowerControlFlow = uiflowcontainer('v0', 'Parent', StatusGrid ...
        , 'FlowDirection', 'RightToLeft');

    LampPanel = uipanel(MainPowerControlFlow, 'BorderType', 'none' ...
        , 'Units', 'points', 'Position', [0, 0, 25, 25]);
    obj.PowerLamp = most.gui.Lamp('Parent', LampPanel);
    set(LampPanel, 'WidthLimits', [25, 25]);

    obj.PowerToggle = uicontrol(MainPowerControlFlow, 'Style', 'togglebutton', 'String', 'Off');
    set(obj.PowerToggle, 'Units', 'points', 'WidthLimits', [40, 40]);

    % Control Row
    ControlGrid = uigridcontainer('v0', 'Parent', ControlFlow ...
        , 'GridSize', [3, 3], 'HorizontalWeight', [2, 4, 1] ...
        );
    set(ControlGrid, 'Units', 'points' ...
        , 'Margin', 5 ...
        , 'HeightLimits', [130,130] ...
        );
    % Gain
    most.gui.staticText('Parent', ControlGrid ...
        , 'String', 'Gain (%):', 'HorizontalAlignment', 'right');
    EditSliderFlow = uiflowcontainer('v0', 'Parent', ControlGrid ...
        , 'FlowDirection', 'LeftToRight' ...
        );
    set(EditSliderFlow, 'Units', 'points', 'Margin', 4, 'Units', 'normalized');
    Edit = uicontrol(EditSliderFlow, 'Style', 'edit');
    set(Edit, 'Units', 'points', 'WidthLimits', [50, 50]);
    Slider = most.gui.slider('Parent', EditSliderFlow);
    obj.GainEditSlider = most.gui.EditSlider('Edit', Edit, 'Slider', Slider);
    obj.GainReportedEdit = uicontrol(ControlGrid ...
        , 'Style', 'edit' ...
        , 'Enable', 'off' ...
        , 'HorizontalAlignment', 'center');

    % Offset
    most.gui.staticText('Parent', ControlGrid ...
        , 'String', 'Gain Offset (V):', 'HorizontalAlignment', 'right');
    EditSliderFlow = uiflowcontainer('v0', 'Parent', ControlGrid ...
        , 'FlowDirection', 'LeftToRight' ...
        );
    set(EditSliderFlow, 'Units', 'points', 'Margin', 4, 'Units', 'normalized');
    Edit = uicontrol(EditSliderFlow, 'Style', 'edit');
    set(Edit, 'Units', 'points', 'WidthLimits', [50, 50]);
    Slider = most.gui.slider('Parent', EditSliderFlow);
    obj.OffsetEditSlider = most.gui.EditSlider('Edit', Edit, 'Slider', Slider);
    obj.OffsetReportedEdit = uicontrol(ControlGrid, 'Style', 'edit' ...
        , 'Enable', 'off' ...
        , 'HorizontalAlignment', 'center');

    % Bandwidth
    most.gui.staticText('Parent', ControlGrid ...
        , 'String', 'Bandwidth:' ...
        , 'HorizontalAlignment', 'right');
    PopupMenuFlow = uiflowcontainer('v0', 'Parent', ControlGrid, 'FlowDirection', 'LeftToRight');
    CenteredMenu = uigridcontainer('v0', 'Parent', PopupMenuFlow ...
        , 'GridSize', [3, 1], 'VerticalWeight', [1, 3, 1] ...
        );
    set(CenteredMenu, 'Units', 'points', 'WidthLimits', [80, 80]);
    uipanel(CenteredMenu, 'BorderType', 'none');
    obj.BandwidthPopupMenu = uicontrol(CenteredMenu, 'Style', 'popupmenu' ...
        , 'String', ["80 MHz", "2.5 MHz", "250 KHz"] ...
        , 'UserData', struct('BandwidthValues', [80e6, 2.5e6, 250e3]));
    obj.BandwidthReportedEdit = uicontrol(ControlGrid ...
        , 'Style', 'edit' ...
        , 'Enable', 'off' ...
        , 'HorizontalAlignment', 'center');
end

function formatAndUpdateWavelengthString(obj, valueString)
    if endsWith(valueString, 'nm')
        valueString = extractBefore(valueString, 'nm');
    end
    valueString = strtrim(valueString);
    value = str2double(valueString);
    if isnan(value)
        value = obj.WavelengthEdit.Value; % revert changes;
    end
    obj.updateWavelength(value);
end

% ---------------------------------------------------------------------------
% Copyright (C) 2025 MBF Bioscience
% 
% ScanImage (R) 2025 is software to be used under the purchased terms
% Code may be modified, but not redistributed without the permission
% of MBF Bioscience
% 
% MBF BIOSCIENCE MAKES NO WARRANTIES, EXPRESS OR IMPLIED, WITH
% RESPECT TO THIS PRODUCT, AND EXPRESSLY DISCLAIMS ANY WARRANTY OF
% MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
% IN NO CASE SHALL MBF BIOSCIENCE BE LIABLE TO ANYONE FOR ANY
% CONSEQUENTIAL OR INCIDENTAL DAMAGES, EXPRESS OR IMPLIED, OR UPON ANY OTHER
% BASIS OF LIABILITY WHATSOEVER, EVEN IF THE LOSS OR DAMAGE IS CAUSED BY
% MBF BIOSCIENCE'S OWN NEGLIGENCE OR FAULT.
% CONSEQUENTLY, MBF BIOSCIENCE SHALL HAVE NO LIABILITY FOR ANY
% PERSONAL INJURY, PROPERTY DAMAGE OR OTHER LOSS BASED ON THE USE OF THE
% PRODUCT IN COMBINATION WITH OR INTEGRATED INTO ANY OTHER INSTRUMENT OR
% DEVICE.  HOWEVER, IF MBF BIOSCIENCE IS HELD LIABLE, WHETHER
% DIRECTLY OR INDIRECTLY, FOR ANY LOSS OR DAMAGE ARISING, REGARDLESS OF CAUSE
% OR ORIGIN, MBF BIOSCIENCE MAXIMUM LIABILITY SHALL NOT IN ANY
% CASE EXCEED THE PURCHASE PRICE OF THE PRODUCT WHICH SHALL BE THE COMPLETE
% AND EXCLUSIVE REMEDY AGAINST MBF BIOSCIENCE.
% ---------------------------------------------------------------------------
