

`define MS_NUM_PHYS_CHANNELS 4
`define MS_PHYS_CHANNEL_WIDTH 14
`define MS_PHYS_CHANNEL_LSZ (`MS_PHYS_CHANNEL_WIDTH-1)
`define MS_PHYS_CHANNEL_BUF_SIZE (`MS_NUM_PHYS_CHANNELS*`MS_PHYS_CHANNEL_WIDTH)
`define MS_PHYS_CHANNEL_BUF_LSZ (`MS_PHYS_CHANNEL_BUF_SIZE-1)
`define MS_NUM_LOGICAL_CHANNELS 4

`define HS_SAMPS_PER_TICK 32
`define HS_NUM_PHYS_CHANNELS 2
`define HS_PHYS_CHANNEL_WIDTH 12
`define HS_PHYS_CHANNEL_LSZ (`HS_PHYS_CHANNEL_WIDTH-1)
`define HS_PHYS_CHANNEL_BUF_SIZE (`HS_SAMPS_PER_TICK*`HS_PHYS_CHANNEL_WIDTH)
`define HS_PHYS_CHANNEL_BUF_LSZ (`HS_PHYS_CHANNEL_BUF_SIZE-1)

`define LOGICAL_CHANNEL_WIDTH 16
`define LOGICAL_CHANNEL_LSZ (`LOGICAL_CHANNEL_WIDTH-1)
`define LOGICAL_CHANNEL_BUF_SIZE (HS_NUM_LOGICAL_CHANNELS*`LOGICAL_CHANNEL_WIDTH)
`define LOGICAL_CHANNEL_BUF_LSZ (`LOGICAL_CHANNEL_BUF_SIZE-1)

`define MAX_NUM_PHY_CHAN 4
`define PHYS_CHAN_BUF_SIZE (`MAX_NUM_PHY_CHAN*`LOGICAL_CHANNEL_WIDTH)
`define PHYS_CHAN_BUF_LSZ (`PHYS_CHAN_BUF_SIZE-1)

`define ACCUM_MULT_A_SZ 28 // signed size
`define ACCUM_MULT_B_SZ 27 // signed size
`define ACCUM_MULT_P_SZ 55 // signed size

`define ACCUM_COEFFICIENT_FIXED_POINT_WIDTH (`ACCUM_MULT_B_SZ-1) // unsigned size
`define ACCUM_COEFFICIENT_FIXED_POINT_LSZ (`ACCUM_COEFFICIENT_FIXED_POINT_WIDTH-1)  // MSB of fixed point width
`define ACCUM_BITS 12
`define ACCUM_CHANNEL_WIDTH (`LOGICAL_CHANNEL_WIDTH+`ACCUM_BITS)
`define ACCUM_CHANNEL_LSZ (`ACCUM_CHANNEL_WIDTH-1)
`define ACCUM_BUF_SIZE (HS_NUM_LOGICAL_CHANNELS*`ACCUM_CHANNEL_WIDTH)
`define ACCUM_BUF_LSZ  (`ACCUM_BUF_SIZE-1)
`define ACCUM_MASK_TABLE_WIDTH (`ACCUM_COEFFICIENT_FIXED_POINT_WIDTH + `ACCUM_BITS)
`define ACCUM_MASK_TABLE_LSZ (`ACCUM_MASK_TABLE_WIDTH-1)

`define TRIGGER_PROCESS_OUT_BITS 20
`define TRIGGER_PROCESS_OUT_PERIOD_TRIGGER_RAW_BIT 0
`define TRIGGER_PROCESS_OUT_PERIOD_TRIGGER_BIT 1
`define TRIGGER_PROCESS_OUT_MID_PERIOD_TRIGGER_BIT 2
`define TRIGGER_PROCESS_OUT_DEL_PERIOD_TRIGGER_BIT 3
`define TRIGGER_PROCESS_OUT_DEL_MID_PERIOD_TRIGGER_BIT 4
`define TRIGGER_PROCESS_OUT_START_TRIGGER_BIT 5
`define TRIGGER_PROCESS_OUT_NEXT_TRIGGER_BIT 6
`define TRIGGER_PROCESS_OUT_STOP_TRIGGER_BIT 7
`define TRIGGER_PROCESS_OUT_PHOTON_PULSE_START_BIT 8
`define TRIGGER_PROCESS_OUT_AUX_TRIGGER_START_BIT 12
`define TRIGGER_PROCESS_OUT_LASER_TRIGGER_BIT 16
`define TRIGGER_PROCESS_OUT_LASER_TRIGGER_RAW_BIT 17
`define TRIGGER_PROCESS_OUT_LASER_TRIGGER_SYNC_BIT 18
`define TRIGGER_PROCESS_OUT_LASER_TRIGGER_SYNC_RAW_BIT 19
`define TRIGGER_PROCESS_OUT_LSZ (`TRIGGER_PROCESS_OUT_BITS-1)


`define STATE_MACHINE_OUT_BITS 73
`define STATE_MACHINE_OUT_SOL_BIT 0
`define STATE_MACHINE_OUT_EOL_BIT 1
`define STATE_MACHINE_OUT_ACQ_CLK_BIT 2
`define STATE_MACHINE_OUT_LINE_CLK_BIT 3
`define STATE_MACHINE_OUT_BEAM_CLK_BIT 4
`define STATE_MACHINE_OUT_ROI_CLK_BIT 5
`define STATE_MACHINE_OUT_SLICE_CLK_BIT 6
`define STATE_MACHINE_OUT_VOLUME_CLK_BIT 7
`define STATE_MACHINE_OUT_CTL_SAMPLE_CLK_BIT 8
`define STATE_MACHINE_OUT_LINE_TS_START_BIT 9
`define STATE_MACHINE_OUT_LSZ (`STATE_MACHINE_OUT_BITS-1)








