function makePanel(obj, Parent)
    most.idioms.mustBeValidObj(obj);
    Flow = uiflowcontainer('v0', 'Parent', Parent);
    set(Flow, 'FlowDirection', 'TopDown');
    Grid = uigridcontainer('v0' ...
        , 'Parent', Flow ...
        , 'GridSize', [2, 2] ...
        , 'HorizontalWeight', [1, 3]);
    set(Grid, 'Units', 'points', 'HeightLimits', [86, 86]);
    
    %% Rack selection
    VerticalCenter = uigridcontainer('v0', 'Parent', Grid ...
        , 'GridSize', [3, 1], 'VerticalWeight', [1, 2, 1] ...
        , 'Margin', 0.1);
    uiflowcontainer('v0', 'Parent', VerticalCenter); % filler
    uicontrol('Parent', VerticalCenter ...
        , 'Style', 'text' ...
        , 'String', 'Rack:' ...
        , 'FontWeight', 'bold' ...
        , 'HorizontalAlignment', 'right');
    VerticalCenter = uigridcontainer('v0', 'Parent', Grid ...
        , 'GridSize', [3, 1], 'VerticalWeight', [1, 2, 1] ...
        , 'Margin', 0.1);
    uiflowcontainer('v0', 'Parent', VerticalCenter); % filler
    obj.RackSelectionMenu = uicontrol('Parent', VerticalCenter ...
        , 'Style', 'popupmenu' ...
        , 'String', 'none' ...
        , 'Value', 1);
    
    %% Device index
    VerticalCenter = uigridcontainer('v0', 'Parent', Grid ...
        , 'GridSize', [3, 1], 'VerticalWeight', [1, 2, 1] ...
        , 'Margin', 0.1);
    uiflowcontainer('v0', 'Parent', VerticalCenter); % filler
    uicontrol('Parent', VerticalCenter ...
        , 'Style', 'text' ...
        , 'String', 'Device:' ...
        , 'FontWeight', 'bold' ...
        , 'HorizontalAlignment', 'right');
    Panel = uipanel('Parent', Grid, 'BorderType', 'none');
    ToggleFlow = uiflowcontainer('v0', 'Parent', Panel);
    set(ToggleFlow, 'FlowDirection', 'LeftToRight');
    [D1Toggle, obj.Device1Toggle] = deal(uicontrol( ...
        'Parent', ToggleFlow ...
        , 'Style', 'togglebutton' ...
        , 'String', 'Left (1)' ...
        ));
    obj.Device1Toggle.Value = obj.Device1Toggle.Max;
    [D2Toggle, obj.Device2Toggle] = deal(uicontrol( ...
        'Parent', ToggleFlow ...
        , 'Style', 'togglebutton' ...
        , 'String', 'Right (2)' ...
        ));
    set([D1Toggle, D2Toggle], 'WidthLimits', [100, 100]);
    D1Toggle.Callback = @(Clicked,~)toggleButton(Clicked, D2Toggle);
    D2Toggle.Callback = @(Clicked,~)toggleButton(Clicked, D1Toggle);
    
    %% Device Properties
    Panel = uipanel('Parent', Flow, 'Title', 'Selected Device', 'Units', 'points');
    [PropertiesText, obj.DevicePropertiesText] = deal(uicontrol( ...
        'Parent', Panel ...
        , 'Style', 'text' ...
        , 'String', '' ... % filled on redraw
        , 'FontName', 'FixedWidth' ...
        , 'FontWeight', 'bold' ...
        , 'HorizontalAlignment', 'left' ...
        , 'Units', 'normalized' ...
        , 'Position', [0, 0, 1, 1]));
    Panel.SizeChangedFcn = @(P,~)set(PropertiesText, 'FontSize', max(min(P.Position(3:4)) / 12, 12));
end

function toggleButton(Clicked, Other)
    Clicked.Value = Clicked.Max;
    if Other.Value ~= Other.Min
        Other.Value = Other.Min;
    end
end
% ---------------------------------------------------------------------------
% Copyright (C) 2025 MBF Bioscience
% 
% ScanImage (R) 2025 is software to be used under the purchased terms
% Code may be modified, but not redistributed without the permission
% of MBF Bioscience
% 
% MBF BIOSCIENCE MAKES NO WARRANTIES, EXPRESS OR IMPLIED, WITH
% RESPECT TO THIS PRODUCT, AND EXPRESSLY DISCLAIMS ANY WARRANTY OF
% MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
% IN NO CASE SHALL MBF BIOSCIENCE BE LIABLE TO ANYONE FOR ANY
% CONSEQUENTIAL OR INCIDENTAL DAMAGES, EXPRESS OR IMPLIED, OR UPON ANY OTHER
% BASIS OF LIABILITY WHATSOEVER, EVEN IF THE LOSS OR DAMAGE IS CAUSED BY
% MBF BIOSCIENCE'S OWN NEGLIGENCE OR FAULT.
% CONSEQUENTLY, MBF BIOSCIENCE SHALL HAVE NO LIABILITY FOR ANY
% PERSONAL INJURY, PROPERTY DAMAGE OR OTHER LOSS BASED ON THE USE OF THE
% PRODUCT IN COMBINATION WITH OR INTEGRATED INTO ANY OTHER INSTRUMENT OR
% DEVICE.  HOWEVER, IF MBF BIOSCIENCE IS HELD LIABLE, WHETHER
% DIRECTLY OR INDIRECTLY, FOR ANY LOSS OR DAMAGE ARISING, REGARDLESS OF CAUSE
% OR ORIGIN, MBF BIOSCIENCE MAXIMUM LIABILITY SHALL NOT IN ANY
% CASE EXCEED THE PURCHASE PRICE OF THE PRODUCT WHICH SHALL BE THE COMPLETE
% AND EXCLUSIVE REMEDY AGAINST MBF BIOSCIENCE.
% ---------------------------------------------------------------------------
